import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,AnimatePresence,useScroll,useSpring} from 'framer-motion';
import {Volume2,VolumeX,ArrowDown,ExternalLink,Terminal,Brain,Code2,Sparkles,X,Zap,PartyPopper,MousePointer2,RefreshCw} from 'lucide-react';
import './style.css';
import './fun.css';
import './reaction.css';

const projects=[
{n:'01',title:'LearnShot',desc:'Anticipation-aware AI that turns long educational lectures into engaging microlearning clips.',stack:['Python','Faster-Whisper','Gemini API','FFmpeg','FastAPI','React.js'],detail:'Finds topic boundaries and high-anticipation moments, then automates transcription, segmentation and delivery.',repo:'https://github.com/KrishnaSathwik23/LearnShot',icon:Brain},
{n:'02',title:'Self Decision AI Engine',desc:'A self-learning decision engine that evaluates predictive models and selects the best algorithm for a dataset.',stack:['Python','Scikit-learn','React.js','ML'],detail:'Combines model evaluation, historical performance and feedback loops into an automated selection pipeline.',repo:'https://github.com/KrishnaSathwik23',icon:Code2},
{n:'03',title:'Health Companion AI',desc:'A RAG-powered healthcare chatbot built around domain-specific documents and semantic retrieval.',stack:['Python','Gemini API','RAG','React.js'],detail:'Uses document chunking, embeddings and semantic search for context-aware responses.',repo:'https://github.com/KrishnaSathwik23',icon:Sparkles}
];
const skills=['Python','C++','SQL','JavaScript','React.js','Node.js','Machine Learning','RAG','DSA','OOP','DBMS','HTML/CSS'];
const reactions=['Ayyayyo!','Enti ra idi?','Abbaa!','Ohooo!','Adirindhi!','Aha!','Chaala baagundhi!','Ayyo ayyo!','Mass ra!','Super ra!','Nuvvu thaggaku!','Idhi vere level!','Em jaruguthundhi ra?','Sare sare!','Malli try cheddam!','Aagandi aagandi!','Nenu ready!','Set ayipoyindhi!','Orey baabu!','Ammo!'];

function App(){
 const{scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:100,damping:30});
 const[sound,setSound]=useState(false),[intro,setIntro]=useState(true),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[chaos,setChaos]=useState(false),[cursor,setCursor]=useState({x:-100,y:-100}),[down,setDown]=useState(false),[reaction,setReaction]=useState('Ayyayyo!');
 const audio=useRef(null);const timer=useRef(null);
 const beep=(type='click')=>{if(!sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!audio.current)audio.current=new C();const c=audio.current;c.resume();const o=c.createOscillator(),g=c.createGain();o.type=type==='success'?'triangle':type==='hover'?'sine':'square';const start=type==='hover'?520:type==='success'?760:260;o.frequency.setValueAtTime(start,c.currentTime);o.frequency.exponentialRampToValueAtTime(type==='success'?1050:type==='hover'?760:130,c.currentTime+.11);g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.045,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.13);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.14)}catch{}};
 const react=(text)=>{const msg=text||reactions[Math.floor(Math.random()*reactions.length)];setReaction(msg);setToast(msg);beep('success');clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),1800)};
 useEffect(()=>{const m=e=>setCursor({x:e.clientX,y:e.clientY}),d=()=>setDown(true),u=()=>setDown(false);window.addEventListener('pointermove',m);window.addEventListener('pointerdown',d);window.addEventListener('pointerup',u);return()=>{window.removeEventListener('pointermove',m);window.removeEventListener('pointerdown',d);window.removeEventListener('pointerup',u)}},[]);
 useEffect(()=>{const onKey=e=>{if(e.ctrlKey&&e.key.toLowerCase()==='k'){e.preventDefault();setChaos(v=>!v);react('Mass mode on! 🔥')}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 return <>
 <motion.div className="progress" style={{scaleX:progress}}/><div className="cursor-dot" style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0) scale(${down?.65:1})`}}/><div className="cursor-ring" style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0) scale(${down?1.5:1})`}}><span>+</span></div>
 <AnimatePresence>{toast&&<motion.div className="toast" initial={{y:-40,opacity:0,scale:.9}} animate={{y:0,opacity:1,scale:1}} exit={{y:-40,opacity:0}}>{toast}</motion.div>}</AnimatePresence>
 <AnimatePresence>{modal&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setModal(null)}><motion.div className="modal" initial={{scale:.8,y:30}} animate={{scale:1,y:0}} exit={{scale:.8,y:30}} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button><span className="modal-kicker">PROJECT INTEL / {modal.n}</span><h2>{modal.title}</h2><p>{modal.detail}</p><div className="modal-stack">{modal.stack.map(x=><span key={x}>{x}</span>)}</div><a className="modal-link" href={modal.repo} target="_blank" rel="noreferrer">OPEN SOURCE <ExternalLink size={16}/></a></motion.div></motion.div>}{/* close modal conditional */}</AnimatePresence>
 {intro&&<motion.div className="intro" initial={{opacity:1}} exit={{opacity:0,scale:1.03}} transition={{duration:.8}}><div className="grain"/><div className="scanlines"/><div className="intro-copy"><span>ఓయ్… SYSTEM BOOT // 2026</span><h1>WELCOME TO<br/><em>KRISHNA'S WORLD</em></h1><p>Portfolio kaadu. <b>Experience.</b></p><button onClick={()=>{setIntro(false);react('Ready aa? Let’s go!')}}>ENTER THE MASS <ArrowDown size={18}/></button><small>Sound effects optional. Fun compulsory.</small></div><div className="boot-log">&gt; booting_ai.exe<br/>&gt; loading_telugu.dll<br/>&gt; loading_interactions...<br/>&gt; sound_engine ✓<br/>&gt; chaos_level: HIGH</div></motion.div>}
 <header><a className="logo" href="#home" onClick={()=>react('Aha! Home ki vachesaav.')}>KS<span>.</span></a><nav><a href="#about" onClick={()=>react('About aa? Chuddam!')}>01 / ABOUT</a><a href="#skills" onClick={()=>react('Skills check chesthunnava?')}>02 / SKILLS</a><a href="#projects" onClick={()=>react('Projects ki veldhaam!')}>03 / WORK</a><a href="#contact" onClick={()=>react('Contact ki ra!')}>04 / CONTACT</a></nav><button className="sound" onClick={()=>setSound(v=>!v)}>{sound?<Volume2/>:<VolumeX/>}<span>{sound?'SOUND ON':'SOUND OFF'}</span></button></header>
 <main id="home" className={chaos?'chaos':''}>
 <section className="hero"><div className="hero-grid"/><div className="hero-scan"/><div className="orb orb1"/><div className="orb orb2"/><div className="hero-left"><p className="eyebrow">CSE IoT · AI BUILDER · CREATIVE TECHNOLOGIST</p><h1>KRISHNA<br/><span>SATHWIK</span></h1><p className="hero-sub">I build <b>AI systems</b>, experiment with software,<br/>and occasionally break things just to understand them.</p><div className="hero-actions"><a href="#projects" onClick={()=>react('Idhi vere level!')}>ENTER THE PROJECTS <ArrowDown size={18}/></a><a href="mailto:krishnasathwik23@gmail.com" className="ghost" onClick={()=>react('Sare, mail pampu!')}>LET'S TALK</a></div><div className="hero-meta"><span><i/> AVAILABLE FOR COOL BUILDS</span><span>INDIA · 2026</span></div></div><div className="portrait-wrap"><div className="portrait-glow"/><div className="portrait-ring"/><img src="https://avatars.githubusercontent.com/u/217095135?v=4" className="portrait" alt="Krishna Sathwik"/><div className="portrait-frame">PORTRAIT_001<br/><b>MAIN CHARACTER</b></div><div className="stamp">AI<br/>×<br/>CODE</div></div><div className="scroll">SCROLL TO CONTINUE ↓</div></section>
 <section className="ticker"><span>TELUGU MODE ON //</span><div>BUG → FIX → BREAK → FIX → DEPLOY → PRAY → REPEAT → &nbsp;</div></section>
 <section className="section reaction-zone"><div className="section-label">BONUS / EVERY CLICK HAS A REACTION</div><div className="reaction-stage"><div><p className="mini-label">CURRENT REACTION</p><motion.h2 key={reaction} initial={{opacity:0,y:20,rotate:-3}} animate={{opacity:1,y:0,rotate:0}}>{reaction}</motion.h2><p>Click anything. Hover anything. The portfolio has opinions.</p></div><button className="reaction-button" onClick={()=>react()}><RefreshCw/> RANDOM TELUGU REACTION</button></div><div className="reaction-grid">{reactions.slice(0,12).map((r,i)=><motion.button key={r} whileHover={{scale:1.07,rotate:i%2?2:-2}} onClick={()=>react(r)}><span>{String(i+1).padStart(2,'0')}</span>{r}</motion.button>)}</div></section>
 <section id="about" className="section about"><div className="section-label">01 / EVARU VEEDU?</div><div className="about-grid"><div><h2>STUDENT.<br/><em>BUILDER.</em><br/>PROBLEM<br/>MAKER.</h2></div><div className="about-copy"><p className="big">Krishna Sathwik Mandavilli builds practical AI and software projects with curiosity, engineering and a little chaos.</p><p>From educational video intelligence to automated model selection and retrieval-augmented AI, the goal is simple: turn weird ideas into working systems.</p><div className="fun-stats"><div><b>03</b><span>AI BUILDS</span></div><div><b>∞</b><span>BUGS DEFEATED</span></div><div><b>01</b><span>CHAOS ENGINE</span></div></div></div></div></section>
 <section id="skills" className="section skills"><div className="section-label">02 / ENTHA SKILL UNNAY?</div><h2>THE TOOLBOX<br/><em>OF DOOM.</em></h2><div className="skill-cloud">{skills.map((s,i)=><motion.button className="skill" key={s} whileHover={{scale:1.1,rotate:i%2?2:-2}} onClick={()=>react(s+' — super!')}><span>{String(i+1).padStart(2,'0')}</span>{s}</motion.button>)}</div><div className="terminal"><Terminal/><span>krishna@portfolio:~$</span><b> python build_cool_stuff.py --with-mass</b><i>✓</i></div></section>
 <section id="projects" className="section projects"><div className="section-label">03 / ASALU MATTER IDHE</div><h2>PROJECTS<br/><em>WITH PLOT.</em></h2>{projects.map((p,i)=>{const Icon=p.icon;return <motion.article className="project" key={p.title} initial={{opacity:0,y:70}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.7}} onClick={()=>{setModal(p);react(i===0?'Abbaa! LearnShot!':i===1?'Ohooo! Decision time!':'Ayyayyo! Health AI!')}}><div className="project-no">{p.n}</div><div className="project-main"><div className="project-top"><span>AI / BUILD</span><span>CLICK FOR INTEL ↗</span></div><h3>{p.title}</h3><p>{p.desc}</p><div className="stack">{p.stack.map(x=><span key={x}>{x}</span>)}</div><div className="project-action">OPEN PROJECT INTEL <Zap size={15}/></div></div><div className={'project-art art'+i}><div className="art-core"><Icon/></div><div className="orbit o1"/><div className="orbit o2"/><span>{i===0?'TRANSCRIBE → THINK → CUT':i===1?'DATA → MODELS → DECISION':'DOCS → EMBEDDINGS → ANSWER'}</span></div></motion.article>})}</section>
 <section className="fun-zone section"><div className="section-label">BONUS / DON'T BE BORING</div><div className="fun-grid"><button className="fun-card" onClick={()=>{setChaos(v=>!v);react(chaos?'Chaos aapeddham.':'MASS MODE ON 🔥')}}><Zap/><strong>MASS MODE</strong><span>Make the UI misbehave.</span></button><button className="fun-card" onClick={()=>react()}><MousePointer2/><strong>DIALOGUE MACHINE</strong><span>Random Telugu reaction every click.</span></button><button className="fun-card" onClick={()=>{react('Party start!');setTimeout(()=>react('Adirindhi!'),350)}}><PartyPopper/><strong>PARTY BUTTON</strong><span>Because why not?</span></button></div></section>
 <section id="contact" className="contact"><div className="contact-no">04</div><p>INKA MATLADUKUNDAAMA?</p><h2>LET'S MAKE<br/><em>SOMETHING CRAZY.</em></h2><a href="mailto:krishnasathwik23@gmail.com" onClick={()=>react('Sare, matladukundham!')}>krishnasathwik23@gmail.com</a><div className="socials"><a href="https://github.com/KrishnaSathwik23" target="_blank" rel="noreferrer" onClick={()=>react('GitHub ki vellam!')}>⌘ GITHUB</a><a href="https://linkedin.com/in/krishnasathwikmandavilli" target="_blank" rel="noreferrer" onClick={()=>react('LinkedIn time!')}>in LINKEDIN</a></div></section>
 </main><footer><span>KRISHNA SATHWIK © 2026</span><span>MADE WITH CODE, CHAOS & TELUGU</span><button onClick={()=>{window.scrollTo({top:0,behavior:'smooth'});react('Back to top!')}}>BACK TO TOP ↑</button></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
